import { describe, expect, it } from "vitest";
import { formatJson, formatMarkdown } from "../formatter.js";
import type { BuildLog } from "../types.js";

function makeBuildLog(overrides?: Partial<BuildLog>): BuildLog {
  return {
    projectPath: "/test/project",
    generatedAt: "2026-01-15T12:00:00Z",
    stats: {
      totalSessions: 2,
      totalMoments: 5,
      decisions: 2,
      pivots: 1,
      emotions: 1,
      directives: 1,
      questions: 0,
      topTools: [{ name: "Edit", count: 10 }],
      dateRange: { from: "2026-01-14", to: "2026-01-15" },
    },
    sessions: [
      {
        sessionId: "sess-1",
        slug: "build-auth",
        date: "2026-01-14",
        startedAt: "2026-01-14T09:00:00Z",
        endedAt: "2026-01-14T11:00:00Z",
        userMessages: 5,
        assistantMessages: 5,
        tools: ["Edit", "Read"],
        moments: [
          {
            type: "DECISION",
            text: "let's go with JWT for auth",
            role: "user",
            timestamp: "2026-01-14T09:30:00Z",
          },
          {
            type: "PIVOT",
            text: "scrap this approach, switching to sessions",
            role: "user",
            timestamp: "2026-01-14T10:00:00Z",
          },
        ],
      },
      {
        sessionId: "sess-2",
        slug: "fix-login",
        date: "2026-01-15",
        startedAt: "2026-01-15T14:00:00Z",
        endedAt: "2026-01-15T15:00:00Z",
        userMessages: 3,
        assistantMessages: 3,
        tools: ["Edit"],
        moments: [
          {
            type: "EMOTION",
            text: "finally this works!",
            role: "user",
            timestamp: "2026-01-15T14:30:00Z",
          },
        ],
      },
    ],
    ...overrides,
  };
}

describe("formatMarkdown", () => {
  it("includes the BUILDARC.md header", () => {
    const md = formatMarkdown(makeBuildLog());
    expect(md).toContain("# BUILDARC.md");
  });

  it("includes summary section with correct stats", () => {
    const md = formatMarkdown(makeBuildLog());
    expect(md).toContain("## Summary");
    expect(md).toContain("**Sessions:** 2");
    expect(md).toContain("**Moments:** 5");
    expect(md).toContain("**Decisions:** 2");
    expect(md).toContain("**Pivots:** 1");
  });

  it("includes date range", () => {
    const md = formatMarkdown(makeBuildLog());
    expect(md).toContain("2026-01-14");
    expect(md).toContain("2026-01-15");
  });

  it("includes moment tags [DECISION], [PIVOT], [EMOTION]", () => {
    const md = formatMarkdown(makeBuildLog());
    expect(md).toContain("[DECISION]");
    expect(md).toContain("[PIVOT]");
    expect(md).toContain("[EMOTION]");
  });

  it("includes session slugs as headers", () => {
    const md = formatMarkdown(makeBuildLog());
    expect(md).toContain("### build-auth");
    expect(md).toContain("### fix-login");
  });

  it("groups sessions by date", () => {
    const md = formatMarkdown(makeBuildLog());
    expect(md).toContain("## 2026-01-14");
    expect(md).toContain("## 2026-01-15");
  });

  it("includes tool names in session metadata", () => {
    const md = formatMarkdown(makeBuildLog());
    expect(md).toContain("Tools: Edit, Read");
  });

  it("includes key moments section", () => {
    const md = formatMarkdown(makeBuildLog());
    expect(md).toContain("## Key moments");
  });

  it("includes generation metadata", () => {
    const md = formatMarkdown(makeBuildLog());
    expect(md).toContain("Generated by buildarc");
    expect(md).toContain("/test/project");
  });
});

describe("formatJson", () => {
  it("produces valid JSON", () => {
    const log = makeBuildLog();
    const json = formatJson(log);
    expect(() => JSON.parse(json)).not.toThrow();
  });

  it("round-trips cleanly", () => {
    const log = makeBuildLog();
    const json = formatJson(log);
    const parsed = JSON.parse(json) as BuildLog;
    expect(parsed.projectPath).toBe(log.projectPath);
    expect(parsed.stats.totalSessions).toBe(log.stats.totalSessions);
    expect(parsed.sessions).toHaveLength(log.sessions.length);
    expect(parsed.sessions[0].moments[0].type).toBe("DECISION");
  });

  it("preserves all moment fields", () => {
    const log = makeBuildLog();
    const json = formatJson(log);
    const parsed = JSON.parse(json) as BuildLog;
    const moment = parsed.sessions[0].moments[0];
    expect(moment).toHaveProperty("type");
    expect(moment).toHaveProperty("text");
    expect(moment).toHaveProperty("role");
    expect(moment).toHaveProperty("timestamp");
  });
});
