import { TYPE_PRIORITY } from "./extractor.js";
import type { BuildLog, Moment, MomentType, Session } from "./types.js";

// ── Markdown formatter ──────────────────────────────────────────────

function formatMomentTag(type: string): string {
  const tags: Record<string, string> = {
    DECISION: "[DECISION]",
    PIVOT: "[PIVOT]",
    EMOTION: "[EMOTION]",
    DIRECTIVE: "[DIRECTIVE]",
    QUESTION: "[QUESTION]",
  };
  return tags[type] ?? `[${type}]`;
}

function formatMoment(moment: Moment): string {
  const tag = formatMomentTag(moment.type);
  const who = moment.role === "user" ? "you" : "claude";
  return `- ${tag} (${who}) ${moment.text}`;
}

function formatSessionMd(session: Session): string {
  const lines: string[] = [];

  lines.push(`### ${session.slug}`);
  lines.push("");
  lines.push(
    `> ${session.userMessages} prompts | ${session.assistantMessages} responses | ${session.moments.length} moments`,
  );
  lines.push(`> ${session.startedAt} → ${session.endedAt}`);

  if (session.tools.length > 0) {
    lines.push(`> Tools: ${session.tools.join(", ")}`);
  }

  lines.push("");

  if (session.moments.length > 0) {
    for (const moment of session.moments) {
      lines.push(formatMoment(moment));
    }
    lines.push("");
  }

  return lines.join("\n");
}

function getTopMoments(sessions: Session[], limit = 15): Moment[] {
  const all: Moment[] = [];
  for (const s of sessions) {
    for (const m of s.moments) all.push(m);
  }
  const score = (m: Moment) => {
    let s = TYPE_PRIORITY[m.type as MomentType] ?? 0;
    if (m.role === "user") s += 3;
    if (m.type === "DIRECTIVE") return 0;
    return s;
  };
  return all
    .filter((m) => score(m) > 0)
    .sort((a, b) => score(b) - score(a))
    .slice(0, limit);
}

export function formatMarkdown(log: BuildLog): string {
  const lines: string[] = [];
  const { stats } = log;

  lines.push("# BUILDARC.md");
  lines.push("");
  lines.push(`> Generated by buildarc on ${log.generatedAt}`);
  lines.push(`> Project: ${log.projectPath}`);
  lines.push("");

  // Stats summary
  lines.push("## Summary");
  lines.push("");
  lines.push(`- **Sessions:** ${stats.totalSessions}`);
  lines.push(`- **Moments:** ${stats.totalMoments}`);
  lines.push(
    `- **Decisions:** ${stats.decisions} | **Pivots:** ${stats.pivots} | **Emotions:** ${stats.emotions}`,
  );
  lines.push(`- **Directives:** ${stats.directives} | **Questions:** ${stats.questions}`);
  lines.push(`- **Date range:** ${stats.dateRange.from} → ${stats.dateRange.to}`);

  if (stats.topTools.length > 0) {
    lines.push(
      `- **Top tools:** ${stats.topTools.map((t) => `${t.name} (${t.count})`).join(", ")}`,
    );
  }

  lines.push("");

  // Key moments — curated shortlist for the storyteller
  const topMoments = getTopMoments(log.sessions);
  if (topMoments.length > 0) {
    lines.push("## Key moments");
    lines.push("");
    lines.push("> These are the highest-signal moments. The full timeline follows below.");
    lines.push("");
    for (const m of topMoments) {
      lines.push(formatMoment(m));
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("");

  // Group sessions by date
  const byDate = new Map<string, Session[]>();
  for (const session of log.sessions) {
    const existing = byDate.get(session.date) ?? [];
    existing.push(session);
    byDate.set(session.date, existing);
  }

  for (const [date, sessions] of byDate) {
    lines.push(`## ${date}`);
    lines.push("");

    for (const session of sessions) {
      if (session.moments.length === 0) continue;
      lines.push(formatSessionMd(session));
    }

    lines.push("---");
    lines.push("");
  }

  return lines.join("\n");
}

// ── JSON formatter ──────────────────────────────────────────────────

export function formatJson(log: BuildLog): string {
  return JSON.stringify(log, null, 2);
}
